### ISSUE TITLE
just asking :)

### ISSUE THREAD

**Issue by damienmillet** [cat394/mongo-request-handler#2]
Hi, 

I'm a French dev and I would ask you about technical difference between  [mongo-request-handler](https://github.com/cat394/mongo-request-handler) and @db/mongo on JSR.

mrh use api call, it's okay, but about performance ?

Ty,

DM

**Comment by cat394** [comment]
Thank you for your question. This package uses the Mongo Data API, a service provided by MongoDB. The Data API is designed to work on the client side as well.

On the other hand, @db/mongo uses a program called the MongoDB driver, which is deeply connected to Node, and is intended to be used completely on the backend.

The MongoDB Data API is simple, allowing you to retrieve and manipulate data stored in MongoDB just by creating a request object and sending a fetch request. This package makes it simple to efficiently create a request object and send a fetch request.

For more information, please refer to the official [MongoDB Data API blog](https://www.mongodb.com/developer/languages/javascript/getting-started-deno-mongodb/).

However, although this Data API is simple, unlike Mongoose, it has the disadvantage that it is difficult to test, and I recently realized that it is very difficult to use in my personal opinion.

Therefore, I was just about to end support for this package.

If you have any questions, please feel free to ask me anything.

**Comment by cat394** [comment]
This is just a side note, but among the client-side database services, I find Firebase Firestore to be the easiest to use. Although it's challenging to make the Firestore SDK type-safe, making it not very compatible with TypeScript, this issue can be resolved by using a great library called Firelord, which allows type-safe interaction with Firestore. If you're interested, please refer to the (Firelord documentation)[https://firelordjs.com/quick_start_web].
